provider: DNSPod
password:
login_token:
domains:
  - domain_name: example.com
    sub_domains:
      - www
      - test
ip_urls: [https://api4.ipify.org, https://api-ipv4.ip.sb/ip, https://ip2location.io/ip, "https://ipinfo.io/ip"]
ipv6_urls: [https://api6.ipify.org, https://api-ipv6.ip.sb/ip, https://ip2location.io/ip, "https://v6.ipinfo.io/ip"]
ip_type: IPv4
interval: 300
resolver: 8.8.8.8
user_agent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.111 Safari/537.36"
ip_interface: eth0
mikrotik:
  enabled: false
  addr: "http://192.168.20.1:81"
  username": "admin"
  password": ""
  interface: "pppoe-out"
web_panel:
  enabled: true
  addr: "0.0.0.0:9000"
  username": "admin"
  password": "123456"
socks5_proxy:
use_proxy: false
debug_info: false
skip_ssl_verify: false
notify:
  telegram:
    enabled: false
    bot_api_key:
    chat_id:
    message_template:
  mail:
    enabled: false
    smtp_server:
    smtp_username:
    smtp_password:
    smtp_port: 25
    send_from:
    send_to:
webhook:
  enabled: false
  url: "http://localhost:5000/api/v1/send"
  request_body: "{ \"domain\": \"{{.Domain}}\", \"ip\": \"{{.CurrentIP}}\", \"ip_type\": \"{{.IPType}}\" }"
