name: Docker Image CI

on:
  push:
    branches:
      - 'auto-image-ci'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get git tag
        # run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
        run: echo ${GITHUB_REF#refs/*/}
      # -
      #   name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1
      # -
      #   name: Login to DockerHub
      #   uses: docker/login-action@v1 
      #   with:
      #     username: ${{ secrets.DOCKER_USER }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      # - name: Build and push the docker image
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: true
      #     tags: timothyye/godns:latest,timothyye/godns:${{ steps.current-time.outputs.formattedTime }}